name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Get Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Configure pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt
      - name: Update cache
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python repo_archive.py
      - name: Update debug.txt
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        #run: python today.py
        run: python debug.py
      - name: Commit
        run: |-
          git status
          git add .
          git diff
          git config --global user.email "dghosh31428@gmail.com"
          git config --global user.name "debghs"
          # git commit -m "Updated README" -a || echo "No changes to commit"
          git commit -m "Update" -a || echo "No changes to commit"
          git push
